/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
  File "tools/train.py", line 162, in <module>
        main()main()

      File "tools/train.py", line 158, in main
  File "tools/train.py", line 158, in main
main()
  File "tools/train.py", line 158, in main
    runner.train()    
runner.train()      File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train

runner.train()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
            model = self.train_loop.run()  # type: ignoremodel = self.train_loop.run()  # type: ignoremodel = self.train_loop.run()  # type: ignore


  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 158, in main
    runner.train()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
        self.runner.val_loop.run()    self.runner.val_loop.run()    
self.runner.val_loop.run()
self.runner.val_loop.run()  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))    
metrics = self.evaluator.evaluate(len(self.dataloader.dataset))  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate

        metrics = self.evaluator.evaluate(len(self.dataloader.dataset))  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
metrics = self.evaluator.evaluate(len(self.dataloader.dataset))

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
            _results = metric.evaluate(size)    _results = metric.evaluate(size)_results = metric.evaluate(size)
_results = metric.evaluate(size)

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 122, in evaluate
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 122, in evaluate

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 122, in evaluate
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 122, in evaluate
            results = collect_results(results = collect_results(results = collect_results(    


  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 931, in collect_results
results = collect_results(  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 931, in collect_results
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 931, in collect_results

  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 931, in collect_results
            return collect_results_cpu(results, size, tmpdir)    return collect_results_cpu(results, size, tmpdir)return collect_results_cpu(results, size, tmpdir)
return collect_results_cpu(results, size, tmpdir)


  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 991, in collect_results_cpu
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 991, in collect_results_cpu
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 991, in collect_results_cpu
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/dist/dist.py", line 991, in collect_results_cpu
    pickle.dump(result_part, f, protocol=2)
        pickle.dump(result_part, f, protocol=2)OSErrorpickle.dump(result_part, f, protocol=2)    

: pickle.dump(result_part, f, protocol=2)[Errno 122] Disk quota exceeded

OSErrorOSError: : [Errno 122] Disk quota exceededOSError[Errno 122] Disk quota exceeded
: 
[Errno 122] Disk quota exceeded
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4434 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4436 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4433) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-03_23:45:35
  host      : skl-a-61.rc.rit.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 4435)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-03_23:45:35
  host      : skl-a-61.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4433)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
