Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 143, in main
    main()
  File "tools/train.py", line 143, in main
    cfg = Config.fromfile(args.config)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 455, in fromfile
    cfg = Config.fromfile(args.config)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 455, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 1653, in _is_lazy_import
    lazy_import is None and not Config._is_lazy_import(filename):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/config/config.py", line 1653, in _is_lazy_import
    parsed_codes = ast.parse(codes_str)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/ast.py", line 47, in parse
    parsed_codes = ast.parse(codes_str)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,    
return compile(source, filename, mode, flags,
  File "<unknown>", line 74
      File "<unknown>", line 74
data_cfg = dict(
        data_cfg = dict(
^
    SyntaxError^
: SyntaxErrorinvalid syntax: 
invalid syntax
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 35340) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-22_14:49:05
  host      : skl-a-47.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 35341)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-22_14:49:05
  host      : skl-a-47.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 35340)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
