/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 154, in main
    runner = Runner.from_cfg(cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 819, in build_model
    model = MODELS.build(model)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/topdown.py", line 55, in __init__
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 154, in main
    runner = Runner.from_cfg(cfg)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 445, in from_cfg
    runner = cls(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 412, in __init__
    self.model = self.build_model(model)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/runner/runner.py", line 819, in build_model
    model = MODELS.build(model)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/topdown.py", line 55, in __init__
    super().__init__(
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 47, in __init__
    super().__init__(
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/pose_estimators/base.py", line 47, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    self.backbone = MODELS.build(backbone)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wt_swinv2_wtm3d.py", line 814, in __init__
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    self.wtm = WTM3D_A(**_wtm_cfg)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/wtm3d_a.py", line 128, in __init__
    obj = obj_cls(**args)  # type: ignore
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/backbones/wt_swinv2_wtm3d.py", line 814, in __init__
    self.wtm1_0 = NATLayer3D(dim, num_heads = num_heads[0], kernel_size=kernel_size, dilation = dilations[0])
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/wtm3d_a.py", line 65, in __init__
    self.attn = NeighborhoodAttention3D(
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/natten/natten3d.py", line 58, in __init__
    self.wtm = WTM3D_A(**_wtm_cfg)
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/wtm3d_a.py", line 128, in __init__
    kernel_size > 1 and kernel_size % 2 == 1
TypeError: '>' not supported between instances of 'tuple' and 'int'
    self.wtm1_0 = NATLayer3D(dim, num_heads = num_heads[0], kernel_size=kernel_size, dilation = dilations[0])
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/utils/wtm3d_a.py", line 65, in __init__
    self.attn = NeighborhoodAttention3D(
  File "/home/nr4325/Desktop/Pose4/mmpose/mmpose/models/natten/natten3d.py", line 58, in __init__
    kernel_size > 1 and kernel_size % 2 == 1
TypeError: '>' not supported between instances of 'tuple' and 'int'
/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23844) of binary: /home/nr4325/miniconda3/envs/pose4/bin/python
Traceback (most recent call last):
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nr4325/miniconda3/envs/pose4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-24_03:54:47
  host      : skl-a-47.rc.rit.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 23845)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-24_03:54:47
  host      : skl-a-47.rc.rit.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23844)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
